# Site settings
name: Atharva Tendle
title: Atharva Tendle | Machine Learning Intern
description:  a Machine Learning Intern and a Master's student trying to utilize the power of 
                       Artificial Intelligence to make the world a better place!
url: https://atharva-tendle.github.io/
email: atharva.tendle13@gmail.com
cover: ./Profile.jpg
resume: ./resume.pdf
social:
  - title: email
    url: mailto:atharva.tendle13@gmail.com
  - title: instagram
    url: https://www.instagram.com/atharvatendle/
  - title: github
    url: https://github.com/atharva-tendle
  - title: linkedin
    url: https://www.linkedin.com/in/atharva-tendle/

# Build settings
markdown: kramdown

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gemspec"
  - "README.md"
  - "node_modules"
  - "build"
  - "gulpfile.js"
  - "package.json"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
